dataset:
  vis:
  - name: ade20k
    disp_name: ade20k_vis
    dir: ade20k/ade20k_vis
    filenames: data_split/ade20k/selected_vis_sample.txt
    resize_to_hw:
    - 480 # original:480
    - 640 # original:640