dataset:
  val:
  - name: ade20k
    disp_name: ade20k_val
    dir: ade20k/ade20k_val
    filenames: data_split/ade20k/filename_list_val_filtered_small_50.txt
    resize_to_hw:
    - 480 # original:480
    - 640 # original:640